dmorton714/intro_PR_Thursday

Dan_Collins.md

Added markdown file with my information

Added markdown file with my information

---

Lisa_Heinecke.md

Contributing my file for Code:KY Thursday thingamajig 🤸‍♀️

Lisa Heinecke

---

Stephen_Riensche.md

Added class profile ;P

---

Jonathan_Laakkonen.md

Hello! Added a short textfile about myself.

Added a short textfile about myself

---

sam_nelson.md

Forked repo, created branch, added md file with information and pushed to branch via git bash

Added markdown file with some information

---

Jacob_Carpenter.md

Added about me file

---

Verdie_Craig.md

yay, finally! Hopefully almost done.

added class intro

---

Jason_Caldwell.md

Practicing more forks this time with a well wish for myself message.

another practice fork

---

Cain_Seriph.md

A space exists between I and made on my local repository, upon pushing again no changes were found between. So I am unsure why it does not exist here.

Added personal readMe file.

---

Dan_Collins.md

The commit message is explanation enough.

edited Dan_Collins.md for example purposes

---

Elizabeth.Lovett.md

Not quite sure how I created 2 files (one empty, one not). Newbie here.

added more than one file with my info

---

Steve_Randall.md

Thursday again

---

Breanna_Klopp.md

I added a markdown file with my information.

Information Markdown File 

---

Robert_Ries.md

Robert Ries here, ready to merge

hello it's me

---

Matt_Iranpour.md

Updated to test

---

Alex_Dameron.md

Shouldn't be a problem this time!

added my file and did not delete all the other files :)

---

Greg_Williams.md

adding my (Greg_Williams) markdown file to the intro_PR_Thursday repo.

Practice github pull

---

Jenya_Cherny.md

Added md file with Jenya's info

Added md file with Jenya's info

---

Joe_Potts.md

Joe_Potts,md commit

---

Larry_Oaks.md

first pull

---

Danny MIracle.md

Create Danny MIracle.md

---

Miazhiewelie_Haralu.md

when i entered git push origin main 
remote: Permission to dmorton714/intro_PR_Thursday.git denied to weliehster.
fatal: unable to access 'https://github.com/dmorton714/intro_PR_Thursday.git/': The requested URL returned error: 403
not sure if it was trying to push changes to the original repository and not to my fork . when i did the git remote -v command it showed the url to the original don intro thursday rep (not sure why?)so had to use the git set url command to my fork. i hope i remember all this stuff because i hardly use a computer lol

add intro_pr_thurday file for miazhiewelie haralu

---

Josh_Owens.md

Added about me markdown file

---

Kinu_pull_req.md

ADDED KINU INFO TO DAN COLLINS FILE FOR PULL REQUEST

ADDED KINU INFO TO DAN COLLINS FILE FOR PULL REQUEST

---

Dennis_Spradlin.md

Added file with opinion about my status thus far.

---

Decy_Mayela.md

This pull request adds an introduction file for Decy to the repository

Added introduction file for Decy
